### ISSUE TITLE
C++ rules not being imported SonarQube (4.1.1)?

### ISSUE THREAD

**Issue by chocks** [coverity/coverity-sonar-plugin#1]
Hi,
I am trying to use the plugin for a C++ project following the setup instructions on the pdf file, but don't see any C++ rules getting imported into the SonarQube (4.1.1) quality profiles. The quality profile shows the Coverity-C++ profile but does not have any rules in it. I am using it with the community C++ plugin. Please help identify if I need to configure something differently.
Thx!

**Comment by jbriggs22** [comment]
This issue should be fixed in release 1.6.0 using the LTS sonarqube versions
