### ISSUE TITLE
technical debt

### ISSUE THREAD

**Issue by simon-watts** [coverity/coverity-sonar-plugin#15]
We have just switched our (Java) project over to using the coverity-sonar-plugin, and can now see the outstanding issues from Coverity in the SonarQube interface.

However - SonarQube now lists zero (0.0%) **Technical Debt Ratio** - which was not the case before.

Should we expect this metric to be set via the plugin?

SonarQube 4.5.4
coverity-sonar-plugin 1.3.0
Coverity Connect 7.6.0

**Comment by jbriggs22** [comment]
I do not believe his was an issue with the Coverity plugin, as far as I know the Coverity plugin did not provide Technical Debt Ratio in SonarQube by default. Some of the rules could have been reconfigured or some other change which had this working on that version.
Please feel free to file a bug or enhancement request with Synopsys support if this is still an issue.
