### ISSUE TITLE
[minor] Coverity icon

### ISSUE THREAD

**Issue by simon-watts** [coverity/coverity-sonar-plugin#16]
This is a cosmetic issue.

The coverity icon added to the footer is taken "from http://www.coverity.com/favicon.ico".  No problem with that - except when your on a secured LAN not connected to the internet, and we have a big red "X" instead!

Can this image be linked from the Coverity Connect server instead?

**Comment by jbriggs22** [comment]
The footer was removed in release 1.6.0
