### ISSUE TITLE
Coverity widget counts absent dismissed issues as outstanding

### ISSUE THREAD

**Issue by zabettina** [coverity/coverity-sonar-plugin#18]
The Coverity widgets outstanding count is not correct.
It counts all issues that are not fixed nor dismissed.
This means that following statuses are counted as outstanding:
- New
- Triaged
- Absent Dismissed

The third status should not be seen as outstanding. It is used for issues that were formerly dismissed and then disappeared, e.g. because the code was refactored.
As a result, more outstanding issues are shown in the widget than really exist in the project.

**Comment by jbriggs22** [comment]
Changes merged in release 1.6.0
