### ISSUE TITLE
Coverity widget does not count parse warnings

### ISSUE THREAD

**Issue by zabettina** [coverity/coverity-sonar-plugin#19]
The Coverity widget does not count some parse warnings as issues:
- PW.PARAM_SET_BUT_NOT_USED
- PW.USELESS_TYPE_QUALIFIER_ON_RETURN_TYPE

If the Coverity server is configured to count them, the number of outstanding issues in Coverity Connect and in SonarQube differs.
There are no rules for these parse warnings in the coverity-sonar-plugin.

Even by adding some rules for such checkers, the issues are not counted.
The problem comes from the function getCheckerProperties() of the Configuration Service.
This function is buggy, as reported in
https://communities.coverity.com/message/6047#6047
it does not report all parse warnings checkers.
The current version of the Web Services API, v9, has removed this function and uses other ways of listing the checkers.
But the coverity-sonar-plugin is still using v6. This version is deprecated in Coverity 7.7.
Is there any plan to upgrade to a more recent version of the API?

Anyway it is possible to fix this problem by a workaround in the plugin, e.g. by creating the missing rules and mapping them to the checkerPropertyDataObj for 'PW.*'.

**Comment by jbriggs22** [comment]
This issue was fixed in release 1.6.0
