### ISSUE TITLE
Timeline plugin does not work wit Coverity metrics

### ISSUE THREAD

**Issue by zabettina** [coverity/coverity-sonar-plugin#20]
When trying to use one of the coverity metrics in the timeline plugin, the following error message shows up instead of the chart:
"An error occurred while trying to display the widget "timeline". Please contact the administrator."

**Comment by jbriggs22** [comment]
Closing this issue since widget support was dropped in SonarQube 6.2. 
Also, the Coverity plugin changed the API used to create metrics in the 1.6.0 plugin (which should improve this).
