### ISSUE TITLE
Cannot issue defects in .h

### ISSUE THREAD

**Issue by zabettina** [coverity/coverity-sonar-plugin#22]
In my examples, everytime a coverity defect appears in a .h file, the issue cannot be created.
The DEBUG level log message says "issuable=null".

Example (with shortened up path):

13:56:06.208 INFO  - Full path after prefix being stripped: C:\JenkinsSlave\workspace...\xyz.h
13:56:06.224 DEBUG - mainEvent=com.coverity.ws.v6.EventDataObj@473f28a1
13:56:06.224 DEBUG - issuable=null
13:56:06.224 DEBUG - ar=org.sonar.api.rules.ActiveRule@7fa30b7d[id=<null>,rule=Rule[id=<null>,name=<null>,key=STATIC_C_PW.INCLUDE_RECURSION_none,configKey=STATIC_C_PW.INCLUDE_RECURSION_none,plugin=coverity-c++,severity=MAJOR,isTemplate=false,status=READY,language=<null>,template=<null>],priority=MAJOR,params=[]]
13:56:06.224 INFO  - Couldn't create issue: 44619

I have several of these examples, and it happens for each defect in a .h and not for defects in .cpp files.

**Comment by jbriggs22** [comment]
This issue was fixed in release 1.6.0
