### ISSUE TITLE
Cannot identify main event, so cannot issue defect

### ISSUE THREAD

**Issue by zabettina** [coverity/coverity-sonar-plugin#23]
I have some coverity defects found by the checker VIRTUAL_DTOR which cannot be issued by the coverity-sonar-plugin.
The problem is that even if there are 4 events found in the defect, none of them is recognized as the "mainEvent". So mainEvent=null, the defect's line cannot be identified and the defect is not issued in SonarQube.
Coverity itself knows that the first event is the main one. But the Web Services API seems not to provide this information correctly to the plugin.
My workaround would be to just set just the first event to be the main, if there are events but it is not clear which one is the main.
This works definitely for VIRTUAL_DTOR.
It is quite important that such defects are not neglected, since they are of Impact = High, that means they are Blockers for SonarQube.

**Comment by jbriggs22** [comment]
This issue should have been resolved in the 1.6.0 release.
