### ISSUE TITLE
SonarQube 6.2 version does not support customizable dashboards and widgets

### ISSUE THREAD

**Issue by gayanpathirage** [coverity/coverity-sonar-plugin#24]
Reference1:  https://jira.sonarsource.com/browse/SONAR-8354
Reference2: https://blog.sonarsource.com/sonarqube-6-x-series-focused-and-efficient/

Will this plugin work in latest 6.2 SonarQube?

**Comment by jairbubbles** [comment]
Well I think this plugin is independant from dashboards and widgets.
But I can't assure you it will work with 6.2 i case they made some API changes (but I doubt they did).

**Comment by gayanpathirage** [comment]
Thanks a lot for the clarification

**Comment by jbriggs22** [comment]
The widget feature was removed from sonarqube 6.2, the Coverity plugin release 1.6.0 will now work with newer versions of sonarqube
