### ISSUE TITLE
Using with Jenkins SonarQube Scanner

### ISSUE THREAD

**Issue by HassanQayyum1993** [coverity/coverity-sonar-plugin#29]
Hi,

Is it compatible with SonarQube Scanner for Jenkins Version 2.10?

**Comment by jbriggs22** [comment]
@HassanQayyum1993 , this has not been specifically tested, but as I understand the "SonarQube Scanner for Jenkins Version 2.10" will be running a supported version of the "SonarQube Scanner". This plugin will support SonarQube Scanner versions 3.0 - 4.0.
